-----------------------------------------
-- Algorithm and Data Structures
-----------------------------------------
  dofile("LuaSubSystem/JRPG/Algorithm/auxiliar_functions.lua")  
  dofile("LuaSubSystem/JRPG/Algorithm/priority_queue.lua")
  dofile("LuaSubSystem/JRPG/Algorithm/statemachine.lua")
  dofile("LuaSubSystem/JRPG/Algorithm/stack.lua")


-----------------------------------------
-- Loads the JRPG meta engine modules
-----------------------------------------   
  dofile("LuaSubSystem/JRPG/Controllers/dialog_controller.lua")  
  dofile("LuaSubSystem/JRPG/Controllers/character_controller.lua")
  dofile("LuaSubSystem/JRPG/Controllers/scene_controller.lua")
  dofile("LuaSubSystem/JRPG/Controllers/sequence_controller.lua")
  dofile("LuaSubSystem/JRPG/Controllers/timer_controller.lua")
  dofile("LuaSubSystem/JRPG/Controllers/minimap_controller.lua")
  dofile("LuaSubSystem/JRPG/Controllers/battle_controller.lua")
  dofile("LuaSubSystem/JRPG/Controllers/quest_controller.lua")
  
