-----------------------------------------
-- Algorithm and Data Structures
-----------------------------------------
  dofile("scripts/JRPGEngine/Algorithm/auxiliar_functions.lua")  
  dofile("scripts/JRPGEngine/Algorithm/priority_queue.lua")
  dofile("scripts/JRPGEngine/Algorithm/statemachine.lua")
  dofile("scripts/JRPGEngine/Algorithm/stack.lua")


-----------------------------------------
-- Loads the JRPG meta engine modules
-----------------------------------------   
  dofile("scripts/JRPGEngine/Controllers/dialog_controller.lua")  
  dofile("scripts/JRPGEngine/Controllers/character_controller.lua")
  dofile("scripts/JRPGEngine/Controllers/scene_controller.lua")
  dofile("scripts/JRPGEngine/Controllers/sequence_controller.lua")
  dofile("scripts/JRPGEngine/Controllers/timer_controller.lua")
  dofile("scripts/JRPGEngine/Controllers/minimap_controller.lua")
  dofile("scripts/JRPGEngine/Controllers/battle_controller.lua")
  dofile("scripts/JRPGEngine/Controllers/quest_controller.lua")
  
